##### Define tensors

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
m1 = [[1.0, 2.0], [3.0, 4.0]]

m2 = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)

m3 = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

In [4]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [5]:
# convert others to tensors
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [6]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


##### Evaluationg ops

In [7]:
x = tf.constant([[1, 2]])

In [8]:
neg_x = tf.negative(x)

In [9]:
print(x)

Tensor("Const_3:0", shape=(1, 2), dtype=int32)


In [10]:
print(neg_x)

Tensor("Neg:0", shape=(1, 2), dtype=int32)


In [11]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(neg_x))

[[1 2]]
[[-1 -2]]


##### Interactive session

In [12]:
sess1 = tf.InteractiveSession()

In [13]:
x1 = tf.constant([[1., 2.]])
neg_op1 = tf.negative(x1)

In [14]:
result = neg_op1.eval()
print(result)

[[-1. -2.]]


In [15]:
sess1.close()

##### Session logging

In [16]:
x2 = tf.constant([[1, 2]])
neg_op2 = tf.negative(x2)

In [17]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    result = sess.run(neg_op2)
    print(result)

[[-1 -2]]


##### Using variables

In [18]:
raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]

In [19]:
spike = tf.Variable(False)
init_op = tf.global_variables_initializer()

In [20]:
with tf.Session() as sess:
    sess.run(init_op)
    for i in range(1, len(raw_data)):
        if raw_data[i] - raw_data[i-1] > 5:
            updater = tf.assign(spike, tf.constant(True))
            updater.eval()
        else:
            tf.assign(spike, tf.constant(False)).eval()
        print("spike: ", spike.eval())

spike:  False
spike:  True
spike:  False
spike:  False
spike:  True
spike:  False
spike:  True


##### Saving variables

In [3]:
import tensorflow as tf
a = tf.Variable(1.0, dtype=tf.float32, name='a')
b = tf.Variable(2.0, dtype=tf.float32, name='b')
c = tf.add(a, b)

init_op = tf.global_variables_initializer()
saver = tf.train.Saver()

In [4]:
with tf.Session() as sess:
    sess.run(init_op)
    result = sess.run(c)
    print(result)
    saver.save(sess, "./test_save")
    print("done.")

3.0
done.


##### Loading variables

In [5]:
with tf.Session() as sess:
    try:
        saver.restore(sess, "./test_save")
        print(c.eval())
    except:
        print("error.")

INFO:tensorflow:Restoring parameters from ./test_save


INFO:tensorflow:Restoring parameters from ./test_save


3.0


##### Using TensorBoard

In [20]:
import numpy as np

raw_data = np.random.normal(10, 1, 100)

In [21]:
print(raw_data[2])

10.0839799987


In [22]:
alpha = tf.constant(0.05)
curr_value = tf.placeholder(tf.float32)
prev_avg = tf.Variable(0.)

update_avg = alpha * curr_value + (1 - alpha) * prev_avg

here is what we care to visualize:

In [23]:
avg_hist = tf.summary.scalar("running_average", update_avg)
value_hist = tf.summary.scalar("incoming_values", curr_value)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("./logs")

In [24]:
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    for i in range(len(raw_data)):
        summary_str, curr_value = sess.run([merged, update_avg], feed_dict={curr_value: raw_data[i]})
        sess.run(tf.assign(prev_avg, curr_value))
        print(raw_data[i], curr_value)
        writer.add_summary(summary_str, i)
        

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-a0573687f2b2>", line 2, in <module>
    curr_value = tf.placeholder(tf.float32)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/enningxie/anaconda3/envs/tensorflow02/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
